#Postgres SQL database properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${POSTGRES_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

#flyway
spring.flyway.locations=classpath:db/migration