spring.application.name=AuctionHouse

#controller prefix
server.servlet.context-path=/api/v1

#jooq
spring.jooq.sql-dialect=POSTGRES

#PostgreSQL database properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${POSTGRES_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}

#flyway
spring.flyway.locations=classpath:db/migration

# JWT
security.jwt.secret=${JWT_SECRET}
security.jwt.issuer=${JWT_ISSUER:auction-house}
security.jwt.audience=${JWT_AUDIENCE:auction-house-api}
security.jwt.access-token-ttl=${JWT_ACCESS_TOKEN_TTL:24h}
